package com.example.ml.export

import com.example.data.model.Dataset
import com.example.data.model.Hyperparameters
import com.example.data.model.TaskType

object CodeExportGenerator {

    fun generatePyTorch(dataset: Dataset, hyperparams: Hyperparameters): String {
        val numFeatures = if (dataset.numericFeatures.isNotEmpty()) dataset.numericFeatures[0].size else dataset.featuresCount
        val isClassification = dataset.taskType != TaskType.REGRESSION
        val numClasses = if (isClassification) kotlin.math.max(2, dataset.classLabels.size) else 1

        val lossFunc = if (isClassification) "nn.CrossEntropyLoss()" else "nn.MSELoss()"
        val targetType = if (isClassification) "torch.long" else "torch.float32"

        val sb = StringBuilder()
        sb.appendLine("# ==============================================================================")
        sb.appendLine("# Model Training Script (PyTorch 2.x)")
        sb.appendLine("# Dataset: ${dataset.title} (${dataset.category.displayName})")
        sb.appendLine("# Task: ${dataset.taskType.displayName} | Features: $numFeatures | Classes: $numClasses")
        sb.appendLine("# Generated by DataForge ML")
        sb.appendLine("# ==============================================================================")
        sb.appendLine()
        sb.appendLine("import torch")
        sb.appendLine("import torch.nn as nn")
        sb.appendLine("from torch.utils.data import Dataset, DataLoader")
        sb.appendLine("from sklearn.model_selection import train_test_split")
        sb.appendLine("from sklearn.preprocessing import StandardScaler")
        sb.appendLine("import numpy as np")
        sb.appendLine()
        sb.appendLine("# 1. Load Feature and Target Tensors")
        sb.appendLine("raw_features = np.array(${dataset.numericFeatures.take(25)}, dtype=np.float32)")
        sb.appendLine("raw_targets = np.array(${dataset.numericTargets.take(25)}, dtype=np.float32)")
        sb.appendLine()
        sb.appendLine("X_train, X_test, y_train, y_test = train_test_split(")
        sb.appendLine("    raw_features, raw_targets, test_size=${hyperparams.testSplitRatio}, random_state=42")
        sb.appendLine(")")
        sb.appendLine()
        sb.appendLine("scaler = StandardScaler()")
        sb.appendLine("X_train = scaler.fit_transform(X_train)")
        sb.appendLine("X_test = scaler.transform(X_test)")
        sb.appendLine()
        sb.appendLine("class MLDataset(Dataset):")
        sb.appendLine("    def __init__(self, X, y):")
        sb.appendLine("        self.X = torch.tensor(X, dtype=torch.float32)")
        sb.appendLine("        self.y = torch.tensor(y, dtype=$targetType)")
        sb.appendLine("    def __len__(self):")
        sb.appendLine("        return len(self.X)")
        sb.appendLine("    def __getitem__(self, idx):")
        sb.appendLine("        return self.X[idx], self.y[idx]")
        sb.appendLine()
        sb.appendLine("train_loader = DataLoader(MLDataset(X_train, y_train), batch_size=${hyperparams.batchSize}, shuffle=True)")
        sb.appendLine("test_loader = DataLoader(MLDataset(X_test, y_test), batch_size=${hyperparams.batchSize}, shuffle=False)")
        sb.appendLine()
        sb.appendLine("# 2. Neural Architecture")
        sb.appendLine("class DataForgeModel(nn.Module):")
        sb.appendLine("    def __init__(self, in_features=$numFeatures, hidden_dim=${hyperparams.hiddenUnits}, out_dim=$numClasses):")
        sb.appendLine("        super().__init__()")
        sb.appendLine("        self.net = nn.Sequential(")
        sb.appendLine("            nn.Linear(in_features, hidden_dim),")
        sb.appendLine("            nn.BatchNorm1d(hidden_dim),")
        sb.appendLine("            nn.ReLU(),")
        sb.appendLine("            nn.Dropout(${hyperparams.dropoutRate}),")
        sb.appendLine("            nn.Linear(hidden_dim, max(8, hidden_dim // 2)),")
        sb.appendLine("            nn.ReLU(),")
        sb.appendLine("            nn.Linear(max(8, hidden_dim // 2), out_dim)")
        sb.appendLine("        )")
        sb.appendLine("    def forward(self, x):")
        sb.appendLine("        return self.net(x)")
        sb.appendLine()
        sb.appendLine("device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')")
        sb.appendLine("model = DataForgeModel().to(device)")
        sb.appendLine("criterion = $lossFunc")
        sb.appendLine("optimizer = torch.optim.Adam(model.parameters(), lr=${hyperparams.learningRate}, weight_decay=${hyperparams.weightDecayL2})")
        sb.appendLine()
        sb.appendLine("# 3. Training Loop")
        sb.appendLine("EPOCHS = ${hyperparams.epochs}")
        sb.appendLine("for epoch in range(1, EPOCHS + 1):")
        sb.appendLine("    model.train()")
        sb.appendLine("    total_loss, correct = 0.0, 0")
        sb.appendLine("    for batch_x, batch_y in train_loader:")
        sb.appendLine("        batch_x, batch_y = batch_x.to(device), batch_y.to(device)")
        sb.appendLine("        optimizer.zero_grad()")
        sb.appendLine("        preds = model(batch_x)")
        sb.appendLine("        loss = criterion(preds.squeeze() if $numClasses == 1 else preds, batch_y)")
        sb.appendLine("        loss.backward()")
        sb.appendLine("        optimizer.step()")
        sb.appendLine("        total_loss += loss.item() * len(batch_x)")
        sb.appendLine("        if ${if (isClassification) "True" else "False"}:")
        sb.appendLine("            correct += (preds.argmax(dim=1) == batch_y).sum().item()")
        sb.appendLine("    train_loss = total_loss / len(X_train)")
        sb.appendLine("    print(f'Epoch [{epoch:02d}/{EPOCHS}] | Train Loss: {train_loss:.4f}')")
        sb.appendLine()
        sb.appendLine("# 4. Save Checkpoint & TorchScript")
        sb.appendLine("torch.save({'model_state': model.state_dict(), 'scaler': scaler}, 'dataforge_${dataset.id}_model.pt')")
        sb.appendLine("scripted_model = torch.jit.script(model.cpu())")
        sb.appendLine("scripted_model.save('dataforge_${dataset.id}_scripted.pt')")
        sb.appendLine("print('Checkpoint and TorchScript saved successfully!')")
        return sb.toString()
    }

    fun generateFastApiServer(dataset: Dataset): String {
        val numFeatures = dataset.featuresCount
        val fields = dataset.featureNames.mapIndexed { idx, name ->
            val cleanName = name.replace(Regex("[^a-zA-Z0-9_]"), "_")
            "    $cleanName: float = 1.0"
        }.joinToString("\n")

        val dictExtraction = dataset.featureNames.mapIndexed { idx, name ->
            val cleanName = name.replace(Regex("[^a-zA-Z0-9_]"), "_")
            "req.$cleanName"
        }.joinToString(", ")

        return """# ==============================================================================
# Production FastAPI Inference Microservice Server
# Dataset: ${dataset.title}
# Generated by DataForge ML
# ==============================================================================

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import numpy as np
import joblib
import uvicorn

app = FastAPI(
    title="DataForge Inference API - ${dataset.title}",
    description="High-throughput real-time prediction microservice endpoint.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class FeatureInput(BaseModel):
$fields

class PredictionResponse(BaseModel):
    predicted_label: str
    confidence_score: float
    status: str = "success"

# Load Model Pipeline Artifact at Startup
pipeline = None

@app.on_event("startup")
def load_model():
    global pipeline
    try:
        pipeline = joblib.load('dataforge_${dataset.id}.pkl')
        print("Model artifact loaded successfully!")
    except Exception as e:
        print(f"Warning: Local artifact not found, using baseline estimator: {e}")

@app.get("/health")
def health_check():
    return {"status": "healthy", "dataset": "${dataset.title}", "features": $numFeatures}

@app.post("/predict", response_model=PredictionResponse)
def predict(req: FeatureInput):
    input_vector = np.array([[$dictExtraction]], dtype=np.float32)
    
    if pipeline is not None:
        pred_class = pipeline.predict(input_vector)[0]
        prob = 0.95
        if hasattr(pipeline, "predict_proba"):
            prob = float(np.max(pipeline.predict_proba(input_vector)))
        return PredictionResponse(predicted_label=str(pred_class), confidence_score=prob)
    else:
        return PredictionResponse(predicted_label="Class 0", confidence_score=0.90)

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
"""
    }

    fun generateOnnxExport(dataset: Dataset, hyperparams: Hyperparameters): String {
        return """# ==============================================================================
# ONNX (Open Neural Network Exchange) Runtime Inference
# Dataset: ${dataset.title}
# ==============================================================================

import numpy as np
import onnxruntime as ort

# 1. Initialize ONNX Runtime Inference Session
session = ort.InferenceSession("dataforge_${dataset.id}.onnx")
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

# 2. Prepare Sample Input Tensor
dummy_input = np.random.randn(1, ${dataset.featuresCount}).astype(np.float32)

# 3. Execute High-Speed Inference
outputs = session.run([output_name], {input_name: dummy_input})
predictions = outputs[0]

print(f"Raw ONNX Output Tensor: {predictions}")
print(f"Predicted Class Index: {np.argmax(predictions, axis=1)[0]}")
"""
    }

    fun generateTensorFlow(dataset: Dataset, hyperparams: Hyperparameters): String {
        val numFeatures = if (dataset.numericFeatures.isNotEmpty()) dataset.numericFeatures[0].size else dataset.featuresCount
        val isClassification = dataset.taskType != TaskType.REGRESSION
        val numClasses = if (isClassification) kotlin.math.max(2, dataset.classLabels.size) else 1
        val finalActivation = if (isClassification) (if (numClasses > 2) "'softmax'" else "'sigmoid'") else "'linear'"
        val lossVal = if (isClassification) (if (numClasses > 2) "'sparse_categorical_crossentropy'" else "'binary_crossentropy'") else "'mse'"

        val sb = StringBuilder()
        sb.appendLine("# ==============================================================================")
        sb.appendLine("# Model Training Script (TensorFlow 2.x / Keras)")
        sb.appendLine("# Dataset: ${dataset.title} (${dataset.category.displayName})")
        sb.appendLine("# Generated by DataForge ML")
        sb.appendLine("# ==============================================================================")
        sb.appendLine()
        sb.appendLine("import tensorflow as tf")
        sb.appendLine("from tensorflow import keras")
        sb.appendLine("from tensorflow.keras import layers")
        sb.appendLine("from sklearn.model_selection import train_test_split")
        sb.appendLine("from sklearn.preprocessing import StandardScaler")
        sb.appendLine("import numpy as np")
        sb.appendLine()
        sb.appendLine("X = np.array(${dataset.numericFeatures.take(25)}, dtype=np.float32)")
        sb.appendLine("y = np.array(${dataset.numericTargets.take(25)}, dtype=np.float32)")
        sb.appendLine()
        sb.appendLine("X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=${hyperparams.testSplitRatio}, random_state=42)")
        sb.appendLine("scaler = StandardScaler()")
        sb.appendLine("X_train = scaler.fit_transform(X_train)")
        sb.appendLine("X_test = scaler.transform(X_test)")
        sb.appendLine()
        sb.appendLine("model = keras.Sequential([")
        sb.appendLine("    layers.Input(shape=($numFeatures,)),")
        sb.appendLine("    layers.Dense(${hyperparams.hiddenUnits}, activation='relu'),")
        sb.appendLine("    layers.BatchNormalization(),")
        sb.appendLine("    layers.Dropout(${hyperparams.dropoutRate}),")
        sb.appendLine("    layers.Dense(max(8, ${hyperparams.hiddenUnits} // 2), activation='relu'),")
        sb.appendLine("    layers.Dense($numClasses, activation=$finalActivation)")
        sb.appendLine("])")
        sb.appendLine()
        sb.appendLine("model.compile(")
        sb.appendLine("    optimizer=keras.optimizers.Adam(learning_rate=${hyperparams.learningRate}),")
        sb.appendLine("    loss=$lossVal,")
        sb.appendLine("    metrics=${if (isClassification) "['accuracy']" else "['mae']"}")
        sb.appendLine(")")
        sb.appendLine()
        sb.appendLine("model.summary()")
        sb.appendLine()
        sb.appendLine("history = model.fit(")
        sb.appendLine("    X_train, y_train,")
        sb.appendLine("    validation_data=(X_test, y_test),")
        sb.appendLine("    epochs=${hyperparams.epochs},")
        sb.appendLine("    batch_size=${hyperparams.batchSize},")
        sb.appendLine("    verbose=1")
        sb.appendLine(")")
        sb.appendLine()
        sb.appendLine("# Export to TensorFlow Lite")
        sb.appendLine("converter = tf.lite.TFLiteConverter.from_keras_model(model)")
        sb.appendLine("converter.optimizations = [tf.lite.Optimize.DEFAULT]")
        sb.appendLine("tflite_model = converter.convert()")
        sb.appendLine("with open('dataforge_model.tflite', 'wb') as f:")
        sb.appendLine("    f.write(tflite_model)")
        sb.appendLine("print('Model exported as dataforge_model.tflite!')")
        return sb.toString()
    }

    fun generateScikitLearn(dataset: Dataset, hyperparams: Hyperparameters): String {
        val isClassification = dataset.taskType != TaskType.REGRESSION

        val sb = StringBuilder()
        sb.appendLine("# ==============================================================================")
        sb.appendLine("# Model Training Script (Scikit-Learn / Joblib)")
        sb.appendLine("# Dataset: ${dataset.title}")
        sb.appendLine("# Generated by DataForge ML")
        sb.appendLine("# ==============================================================================")
        sb.appendLine()
        sb.appendLine("import numpy as np")
        sb.appendLine("from sklearn.model_selection import train_test_split")
        sb.appendLine("from sklearn.preprocessing import StandardScaler")
        sb.appendLine("from sklearn.pipeline import Pipeline")
        sb.appendLine("import joblib")
        sb.appendLine()
        sb.appendLine("X = np.array(${dataset.numericFeatures.take(25)})")
        sb.appendLine("y = np.array(${dataset.numericTargets.take(25)})")
        sb.appendLine()
        sb.appendLine("X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=${hyperparams.testSplitRatio}, random_state=42)")
        sb.appendLine()

        if (isClassification) {
            sb.appendLine("from sklearn.ensemble import RandomForestClassifier")
            sb.appendLine("from sklearn.metrics import classification_report")
            sb.appendLine()
            sb.appendLine("model = RandomForestClassifier(n_estimators=100, max_depth=${hyperparams.maxTreeDepth}, random_state=42)")
            sb.appendLine("pipeline = Pipeline([('scaler', StandardScaler()), ('clf', model)])")
            sb.appendLine("pipeline.fit(X_train, y_train)")
            sb.appendLine("y_pred = pipeline.predict(X_test)")
            sb.appendLine("print(classification_report(y_test, y_pred))")
        } else {
            sb.appendLine("from sklearn.linear_model import Ridge")
            sb.appendLine("from sklearn.metrics import mean_squared_error, r2_score")
            sb.appendLine()
            sb.appendLine("model = Ridge(alpha=1.0)")
            sb.appendLine("pipeline = Pipeline([('scaler', StandardScaler()), ('reg', model)])")
            sb.appendLine("pipeline.fit(X_train, y_train)")
            sb.appendLine("y_pred = pipeline.predict(X_test)")
            sb.appendLine("print('R2 Fit:', r2_score(y_test, y_pred))")
            sb.appendLine("print('MSE:', mean_squared_error(y_test, y_pred))")
        }

        sb.appendLine()
        sb.appendLine("joblib.dump(pipeline, 'dataforge_${dataset.id}.pkl')")
        sb.appendLine("print('Saved pipeline artifact!')")
        return sb.toString()
    }

    fun generateCsv(dataset: Dataset): String {
        if (dataset.sampleRows.isEmpty()) return "id,feature_1,feature_2,target\n1,0.5,1.2,0\n"
        val headers = dataset.sampleRows[0].keys.toList()
        val headerLine = headers.joinToString(",")
        val rowLines = dataset.sampleRows.map { row ->
            headers.joinToString(",") { h ->
                val v = row[h] ?: ""
                if (v.contains(",") || v.contains("\"")) "\"${v.replace("\"", "\"\"")}\"" else v
            }
        }
        return (listOf(headerLine) + rowLines).joinToString("\n")
    }

    fun generateJson(dataset: Dataset): String {
        val rows = dataset.sampleRows.map { row ->
            val entries = row.map { (k, v) -> "\"$k\": \"$v\"" }.joinToString(", ")
            "  { $entries }"
        }.joinToString(",\n")
        return "[\n$rows\n]"
    }
}

